/* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *      1: 1
 *      3: 1,3
 *      6: 1,2,3,6
 *     10: 1,2,5,10
 *     15: 1,3,5,15
 *     21: 1,3,7,21
 *    28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred divisors?
 */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>

unsigned long long* sievePrimes(unsigned long long* n)
{
  if (*n < 2) return NULL;

  char primes[(*n+1)/2];
  int i,j;

  for (i=1; i<(*n+1)/2; ++i) // initialize sieve
    primes[i] = 'p';

  for (i=1; i <= (sqrt(*n)+1)/2; ++i) // mark nonprimes with 'x'
    if (primes[i] == 'p')
      for (j=2*i*(i+1); j<(*n+1)/2; j+=(2*i+1))
        primes[j] = 'x';

  unsigned long long* p = malloc (sizeof(unsigned long long) * ((*n+1)/2));
  j=0;
  p[j++] = 2;

  for (i=1; i<(*n+1)/2; ++i)
    if (primes[i] == 'p')
      p[j++] = 2*i+1;

  *n = j;
  return realloc(p, j*(sizeof(unsigned long long)));
}

int main()
{
  int tNum = 1, nNum = 1, divisors = 0, tNum2, exponent, i;
  unsigned long long* p = malloc(sizeof(unsigned long long));
  *p = 65500;
  unsigned long long* primes = sievePrimes(p);

  while (divisors <= 500)
  {
    nNum++; // next natural number
    tNum2 = tNum+=nNum; // next triangle number
    divisors = 1; // so we can *=

    for (i=0; i<*p; ++i)
    {
      if (primes[i]*primes[i] > tNum2) // current prime greater than sqrt(tNum), so it's last divisor and has multiple 1
      {
        divisors*=2; // whatever it is, it'll multiply everything by (1+1)==2. don't need to actually find it
        break;
      }

      exponent = 1; // formula is (a_1+1)*(a_2+1)...(a_n+1), so start with the +1
      while (tNum2 % primes[i] == 0)
      {
        ++exponent;
        tNum2 /= primes[i];
      }
      if (exponent>1)
        divisors *= exponent; // multiply next term in formula

      if (tNum2 == 1) // check if we've fully factored our number
        break;
    }
  }
  printf("answer is %d\n", tNum);
}

