/* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *      1: 1
 *      3: 1,3
 *      6: 1,2,3,6
 *     10: 1,2,5,10
 *     15: 1,3,5,15
 *     21: 1,3,7,21
 *    28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred divisors?
 */

#include <stdio.h>

int main()
{
  unsigned int i=6,j,divisors;
  unsigned long long triangle=21;

  while (++i)
  {
    divisors=1;
    triangle+=i;
    for (j=1; j<=triangle/2; ++j)
    {
      if (triangle % j == 0)
      {  ++divisors;
        //printf("%llu/%u ", triangle, j);
      }
    }
    if (triangle == 28)
      printf("%llu has %d ", triangle, divisors);
    if (divisors > 500)
    {
      printf("answer is %llu\n", triangle);
      break;
    }
  }

}


